name: "Hello world workflow"

# controls when the action will run, Triggers the workflow on push some to master or
# production branch
on:
  push:
    branches:
      - master
      - production

jobs:
  hello_word:
    runs-on: ubuntu-latest
    steps:
      - name: "Print hello world"
        run: echo "hello world"

      - name: "Print Current Date"
        run: date

  practice_pro:
    runs-on: ubuntu-latest
    steps:
      - name: "Print the Gautam Agrawal"
        run: echo "hello
